import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronRight, ClipboardCheck, HeartPulse, Pencil, Plus, Search, UserRound, X } from "lucide-react";

const PLAN_STATUS = { DRAFT: "草稿", PUBLISHED: "执行中", SUPERSEDED: "已失效", CANCELLED: "已停用" };
const TASK_STATUS = { PENDING: "待处理", IN_PROGRESS: "进行中", PENDING_CONFIRMATION: "待确认", COMPLETED: "已完成", EXCEPTION: "异常", OVERDUE: "已逾期", CANCELLED: "已取消" };

const dateToday = () => new Date().toISOString().slice(0, 10);

function planView(plan, residents, members) {
  const resident = residents.find((item) => String(item.id) === String(plan.residentId));
  const member = members.find((item) => String(item.userId || item.id) === String(plan.ownerId || plan.assigneeId));
  return { ...plan, label: plan.planName || plan.name, residentName: resident?.name || `长者 #${plan.residentId}`, memberName: member?.nickName || member?.name || `成员 #${plan.ownerId || plan.assigneeId || "-"}`, statusLabel: PLAN_STATUS[plan.status] || plan.status };
}

function taskView(task, residents, members) {
  const resident = residents.find((item) => String(item.id) === String(task.residentId));
  const member = members.find((item) => String(item.userId || item.id) === String(task.assigneeId));
  return { ...task, residentName: resident?.name || `长者 #${task.residentId}`, memberName: member?.nickName || member?.name || `成员 #${task.assigneeId}`, statusLabel: TASK_STATUS[task.status] || task.status, time: String(task.scheduledAt || "").slice(11, 16) || "--:--" };
}

export function GatewayCareWorkspace({ careApi, residentApi, systemApi, onAnnounce }) {
  const [plans, setPlans] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [followUps, setFollowUps] = useState([]);
  const [handovers, setHandovers] = useState([]);
  const [templates, setTemplates] = useState([]);
  const [residents, setResidents] = useState([]);
  const [members, setMembers] = useState([]);
  const [serviceRecords, setServiceRecords] = useState([]);
  const [selectedPlanId, setSelectedPlanId] = useState("");
  const [taskFilter, setTaskFilter] = useState("ALL");
  const [serviceFilters, setServiceFilters] = useState({ residentId: "", serviceDate: "", executorId: "" });
  const [form, setForm] = useState(null);
  const [working, setWorking] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setError("");
    try {
      const [rawPlans, rawTasks, rawFollowUps, rawHandovers, rawResidents, rawMembers, rawRecords] = await Promise.all([
        careApi.listPlans(), careApi.listTasks(), careApi.listTaskFollowUps(), careApi.listShiftHandovers(),
        residentApi.listResidents(), systemApi.listMembers(), careApi.listServiceRecords(),
      ]);
      setResidents(rawResidents); setMembers(rawMembers); setPlans(rawPlans); setTasks(rawTasks); setFollowUps(rawFollowUps); setHandovers(rawHandovers); setServiceRecords(rawRecords);
    } catch (requestError) { setError(requestError.message || "护理数据加载失败"); }
  }, [careApi, residentApi, systemApi]);

  useEffect(() => { void load(); }, [load]);

  const run = async (action, message) => {
    setWorking(true);
    try { await action(); await load(); setForm(null); onAnnounce(message); }
    catch (requestError) { await load(); onAnnounce(requestError.status === 409 ? "记录已变化，已刷新最新数据" : (requestError.message || "操作未提交")); }
    finally { setWorking(false); }
  };

  const loadTemplates = async (planId) => {
    setSelectedPlanId(String(planId));
    try { setTemplates(await careApi.listTaskTemplates(planId)); } catch (requestError) { onAnnounce(requestError.message || "模板读取失败"); }
  };
  const loadServiceRecords = async () => {
    try { setServiceRecords(await careApi.listServiceRecords({ residentId: serviceFilters.residentId || undefined, serviceDate: serviceFilters.serviceDate || undefined, executorId: serviceFilters.executorId || undefined })); } catch (requestError) { onAnnounce(requestError.message || "服务记录读取失败"); }
  };

  const visiblePlans = useMemo(() => plans.map((plan) => planView(plan, residents, members)), [members, plans, residents]);
  const visibleTasks = useMemo(() => tasks.map((task) => taskView(task, residents, members)).filter((task) => taskFilter === "ALL" || task.status === taskFilter), [members, residents, taskFilter, tasks]);
  const selectedPlan = plans.find((plan) => String(plan.id) === selectedPlanId);
  const eligibleMembers = members.filter((member) => String(member.status ?? "0") === "0" || member.status === "已启用");
  const openFollowUps = followUps.filter((item) => item.status === "OPEN");

  const openPlanForm = (plan) => setForm({ type: "plan", plan, value: { planName: plan?.planName || plan?.name || "", frequencyText: plan?.frequencyText || plan?.frequency || "每日", startDate: plan?.startDate || dateToday(), endDate: plan?.endDate || "" } });
  const openTemplateForm = (template) => setForm({ type: "template", template, value: { taskName: template?.taskName || "", scheduledTime: template?.scheduledTime || "08:00", assigneeId: String(template?.assigneeId || "") } });

  if (error) return <section className="module-page care-workspace"><div className="empty-inline">{error}</div><button type="button" className="button secondary" onClick={() => void load()}>重新加载</button></section>;
  return <section className="module-page care-workspace">
    <div className="module-hero"><div><p className="eyebrow"><span />服务执行闭环</p><h1>护理执行中心</h1><p>计划、模板、任务、服务记录、异常跟进和班次交接均使用当前机构真实数据。</p></div><div className="module-hero-actions"><button type="button" className="button secondary" onClick={() => setForm({ type: "generate", value: { serviceDate: dateToday() } })}>生成每日任务</button><button type="button" className="button primary" onClick={() => openPlanForm(null)}><Plus size={17} />新建护理计划</button></div></div>
    <section className="care-kpis"><article><span>待处理任务</span><strong>{tasks.filter((task) => task.status === "PENDING" || task.status === "OVERDUE").length}</strong><small>来自当前机构任务队列</small></article><article><span>开放跟进</span><strong>{openFollowUps.length}</strong><small>异常需结案后交接</small></article><article><span>服务记录</span><strong>{serviceRecords.length}</strong><small>当前筛选结果</small></article></section>
    <div className="care-execution-grid"><section className="panel execution-panel"><div className="panel-heading"><div><h2>任务队列</h2><p>开始、完成和异常操作均携带版本与幂等键</p></div><button type="button" className="text-action" onClick={() => setForm({ type: "task", value: { planId: "", taskName: "", scheduledAt: "", assigneeId: "" } })}><Plus size={15} />手工任务</button></div><div className="filter-row">{[["ALL", "全部"], ...Object.entries(TASK_STATUS).map(([code, label]) => [code, label])].map(([code, label]) => <button type="button" key={code} className={taskFilter === code ? "filter active" : "filter"} onClick={() => setTaskFilter(code)}>{label}</button>)}</div><div className="execution-list">{visibleTasks.length ? visibleTasks.map((task) => <article key={task.id}><div className="execution-time"><i className={task.status === "EXCEPTION" || task.status === "OVERDUE" ? "high" : "normal"} />{task.time}</div><div className="execution-task"><b>{task.taskName}</b><span>{task.residentName} · {task.memberName}</span></div><span className="record-status">{task.statusLabel}</span>{task.status === "PENDING" && <button type="button" className="text-action" onClick={() => void run(() => careApi.startTask(task.id, { taskVersion: task.version }), "任务已开始")}>开始</button>}{["PENDING", "IN_PROGRESS", "PENDING_CONFIRMATION"].includes(task.status) && <><button type="button" title="完成" onClick={() => setForm({ type: "complete", task })}><Check size={16} /></button><button type="button" title="异常" onClick={() => setForm({ type: "exception", task })}><AlertTriangle size={16} /></button></>}</article>) : <p className="empty-inline">暂无匹配任务</p>}</div></section>
      <aside className="panel plan-panel"><div className="panel-heading"><div><h2>护理计划</h2><p>计划状态控制任务生成</p></div><span className="detail-count">{visiblePlans.length} 个</span></div><div className="care-plan-list">{visiblePlans.map((plan) => <article key={plan.id}><span className="plan-icon"><HeartPulse size={16} /></span><div><b>{plan.label}</b><small>{plan.residentName} · {plan.memberName}</small><span>{plan.statusLabel}</span></div><button type="button" title="查看模板" onClick={() => void loadTemplates(plan.id)}><ChevronRight size={17} /></button>{plan.status === "DRAFT" && <button type="button" className="text-action" onClick={() => openPlanForm(plan)}>编辑</button>}{plan.status === "DRAFT" && <button type="button" className="text-action" onClick={() => void run(() => careApi.publishPlan(plan.id, plan.version), "计划已发布")}>发布</button>}{plan.status === "PUBLISHED" && <button type="button" className="text-action danger" onClick={() => void run(() => careApi.cancelPlan(plan.id, plan.version), "计划已停用")}>停用</button>}</article>)}</div></aside></div>
    {selectedPlanId && <section className="panel resident-gateway-form"><div className="panel-heading compact"><div><h2>计划 #{selectedPlanId} 的任务模板</h2><p>模板停用后不再生成新任务</p></div><div><button type="button" className="text-action" onClick={() => openTemplateForm(null)}><Plus size={15} />添加模板</button></div></div>{templates.length ? <div className="execution-list">{templates.map((template) => <article key={template.id}><div className="execution-task"><b>{template.taskName}</b><span>{template.scheduledTime} · {members.find((member) => String(member.userId || member.id) === String(template.assigneeId))?.nickName || `成员 #${template.assigneeId}`}</span></div><span className="record-status">{template.active ? "启用" : "已停用"}</span>{template.active && <button type="button" className="text-action" onClick={() => openTemplateForm(template)}>编辑</button>}{template.active && <button type="button" className="text-action danger" onClick={() => void run(() => careApi.deactivateTaskTemplate(template.id, template.version), "模板已停用")}>停用</button>}</article>)}</div> : <p className="empty-inline">暂无模板</p>}</section>}
    {form && <CareForm form={form} plans={visiblePlans} tasks={tasks} residents={residents} members={eligibleMembers} working={working} onClose={() => setForm(null)} onSubmit={(action, message) => void run(action, message)} careApi={careApi} selectedPlanId={selectedPlanId} />}
    <section className="panel service-record-panel"><div className="panel-heading"><div><h2>服务记录查询</h2><p>按长者、服务日期和执行成员筛选当前机构记录</p></div><Search size={18} /></div><div className="record-fields compact-fields"><label>长者<select value={serviceFilters.residentId} onChange={(event) => setServiceFilters({ ...serviceFilters, residentId: event.target.value })}><option value="">全部长者</option>{residents.map((resident) => <option key={resident.id} value={resident.id}>{resident.name}</option>)}</select></label><label>服务日期<input type="date" value={serviceFilters.serviceDate} onChange={(event) => setServiceFilters({ ...serviceFilters, serviceDate: event.target.value })} /></label><label>执行成员<select value={serviceFilters.executorId} onChange={(event) => setServiceFilters({ ...serviceFilters, executorId: event.target.value })}><option value="">全部成员</option>{eligibleMembers.map((member) => <option key={member.userId || member.id} value={member.userId || member.id}>{member.nickName || member.name || member.userName}</option>)}</select></label><button type="button" className="button secondary" onClick={() => void loadServiceRecords()}>查询</button></div><div className="execution-list">{serviceRecords.length ? serviceRecords.map((record) => <article key={record.id}><div className="execution-task"><b>{record.resultNote || "服务记录"}</b><span>长者 #{record.residentId} · 执行成员 #{record.executorId} · {String(record.completedAt || record.serviceDate || "").slice(0, 16)}</span></div></article>) : <p className="empty-inline">暂无服务记录</p>}</div></section>
    <section className="care-execution-grid"><section className="panel execution-panel"><div className="panel-heading"><div><h2>异常跟进</h2><p>开放异常必须结案后才能提交交接</p></div></div><div className="execution-list">{followUps.length ? followUps.map((item) => <article key={item.id}><div className="execution-task"><b>任务 #{item.taskId} · 长者 #{item.residentId}</b><span>{item.exceptionReason}</span></div><span className="record-status">{item.status === "RESOLVED" ? "已结案" : "待处理"}</span>{item.status === "OPEN" && <button type="button" className="text-action" onClick={() => setForm({ type: "resolve", followUp: item })}>结案</button>}</article>) : <p className="empty-inline">暂无跟进项</p>}</div></section><aside className="panel plan-panel"><div className="panel-heading"><div><h2>班次交接</h2><p>仅可提交已完成或已说明异常的任务</p></div><button type="button" className="text-action" onClick={() => setForm({ type: "handover", value: { shiftDate: dateToday(), shiftCode: "DAY", toUserId: "", note: "", taskIds: [] } })}><Plus size={15} />新建</button></div><div className="care-plan-list">{handovers.map((handover) => <article key={handover.id}><div><b>{handover.shiftDate} · {handover.shiftCode}</b><small>接班成员 #{handover.toUserId} · {handover.status}</small></div>{handover.status === "DRAFT" && <button type="button" className="text-action" onClick={() => void run(() => careApi.submitShiftHandover(handover.id, handover.version), "交接已提交")}>提交</button>}</article>)}</div></aside></section>
  </section>;
}

function CareForm({ form, plans, tasks, residents, members, working, onClose, onSubmit, careApi, selectedPlanId }) {
  const [value, setValue] = useState(form.value || {});
  const update = (key, next) => setValue((current) => ({ ...current, [key]: next }));
  if (form.type === "plan") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); const action = form.plan ? careApi.updatePlan(form.plan.id, { ...value, planVersion: form.plan.version, endDate: value.endDate || undefined }) : careApi.createPlan({ ...value, residentId: Number(value.residentId), endDate: value.endDate || undefined }); onSubmit(() => action, form.plan ? "护理计划已更新" : "护理计划草稿已创建"); }}><div className="panel-heading compact"><div><h2>{form.plan ? "编辑护理计划" : "新建护理计划"}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><div className="record-fields">{form.plan ? <label>服务长者<input readOnly value={form.plan.residentId} /> </label> : <label>服务长者<select required value={value.residentId || ""} onChange={(event) => update("residentId", event.target.value)}><option value="">请选择</option>{residents.map((resident) => <option key={resident.id} value={resident.id}>{resident.name}</option>)}</select></label>}<label>计划名称<input required value={value.planName || ""} onChange={(event) => update("planName", event.target.value)} /></label><label>服务频次<input required value={value.frequencyText || ""} onChange={(event) => update("frequencyText", event.target.value)} /></label><label>开始日期<input required type="date" value={value.startDate || ""} onChange={(event) => update("startDate", event.target.value)} /></label><label>结束日期<input type="date" value={value.endDate || ""} onChange={(event) => update("endDate", event.target.value)} /></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>{working ? "保存中" : "保存"}</button></div></form>;
  if (form.type === "template") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); const action = form.template ? careApi.updateTaskTemplate(form.template.id, { ...value, assigneeId: Number(value.assigneeId), templateVersion: form.template.version }) : careApi.createTaskTemplate({ planId: Number(selectedPlanId), ...value, assigneeId: Number(value.assigneeId) }); onSubmit(() => action, form.template ? "模板已更新" : "模板已创建"); }}><div className="panel-heading compact"><div><h2>{form.template ? "编辑任务模板" : "添加任务模板"}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><div className="record-fields"><label>任务名称<input required value={value.taskName || ""} onChange={(event) => update("taskName", event.target.value)} /></label><label>计划时间<input required type="time" value={value.scheduledTime || "08:00"} onChange={(event) => update("scheduledTime", event.target.value)} /></label><label>执行成员<select required value={value.assigneeId || ""} onChange={(event) => update("assigneeId", event.target.value)}><option value="">请选择成员</option>{members.map((member) => <option key={member.userId || member.id} value={member.userId || member.id}>{member.nickName || member.name || member.userName}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>{working ? "保存中" : "保存"}</button></div></form>;
  if (form.type === "generate") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); onSubmit(() => careApi.generateTasks(value.serviceDate), "每日任务已生成"); }}><div className="panel-heading compact"><div><h2>生成每日任务</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><label>服务日期<input required type="date" value={value.serviceDate || dateToday()} onChange={(event) => update("serviceDate", event.target.value)} /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>生成</button></div></form>;
  if (form.type === "complete" || form.type === "exception") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); const note = new FormData(event.currentTarget).get("note"); if (!String(note || "").trim()) return; onSubmit(() => form.type === "complete" ? careApi.completeTask(form.task.id, { taskVersion: form.task.version, resultNote: String(note) }) : careApi.markTaskException(form.task.id, { taskVersion: form.task.version, exceptionReason: String(note) }), form.type === "complete" ? "任务已完成并写入服务记录" : "任务已标记异常"); }}><div className="panel-heading compact"><div><h2>{form.type === "complete" ? "完成护理任务" : "标记任务异常"}</h2><p>{form.task.taskName}</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><label>{form.type === "complete" ? "服务记录" : "异常说明"}<textarea required name="note" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>提交</button></div></form>;
  if (form.type === "task") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); onSubmit(() => careApi.createTask({ ...value, planId: Number(value.planId), assigneeId: Number(value.assigneeId) }), "护理任务已创建"); }}><div className="panel-heading compact"><div><h2>新建护理任务</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><div className="record-fields"><label>护理计划<select required value={value.planId || ""} onChange={(event) => update("planId", event.target.value)}><option value="">请选择</option>{plans.filter((plan) => plan.status === "PUBLISHED").map((plan) => <option key={plan.id} value={plan.id}>{plan.label} · {plan.residentName}</option>)}</select></label><label>任务名称<input required value={value.taskName || ""} onChange={(event) => update("taskName", event.target.value)} /></label><label>执行时间<input required type="datetime-local" value={value.scheduledAt || ""} onChange={(event) => update("scheduledAt", event.target.value)} /></label><label>执行成员<select required value={value.assigneeId || ""} onChange={(event) => update("assigneeId", event.target.value)}><option value="">请选择成员</option>{members.map((member) => <option key={member.userId || member.id} value={member.userId || member.id}>{member.nickName || member.name || member.userName}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>创建</button></div></form>;
  if (form.type === "resolve") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); const note = String(new FormData(event.currentTarget).get("resolutionNote") || "").trim(); if (!note) return; onSubmit(() => careApi.resolveTaskFollowUp(form.followUp.id, { followUpVersion: form.followUp.version, resolutionNote: note }), "异常跟进已结案"); }}><div className="panel-heading compact"><div><h2>结案异常跟进</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><label>结案说明<textarea required name="resolutionNote" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>结案</button></div></form>;
  if (form.type === "handover") return <form className="panel resident-gateway-form" onSubmit={(event) => { event.preventDefault(); if (!value.taskIds?.length) return; onSubmit(() => careApi.createShiftHandover({ ...value, toUserId: Number(value.toUserId) }), "班次交接草稿已创建"); }}><div className="panel-heading compact"><div><h2>新建班次交接</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X size={17} /></button></div><div className="record-fields"><label>交接日期<input required type="date" value={value.shiftDate || dateToday()} onChange={(event) => update("shiftDate", event.target.value)} /></label><label>班次代码<input required value={value.shiftCode || "DAY"} onChange={(event) => update("shiftCode", event.target.value)} /></label><label>接班成员<select required value={value.toUserId || ""} onChange={(event) => update("toUserId", event.target.value)}><option value="">请选择成员</option>{members.map((member) => <option key={member.userId || member.id} value={member.userId || member.id}>{member.nickName || member.name || member.userName}</option>)}</select></label></div><label>交接说明<textarea required value={value.note || ""} onChange={(event) => update("note", event.target.value)} /></label><fieldset><legend>交接任务</legend>{tasksForHandover(tasks).map((task) => <label key={task.id}><input type="checkbox" checked={value.taskIds?.includes(task.id)} onChange={(event) => update("taskIds", event.target.checked ? [...(value.taskIds || []), task.id] : (value.taskIds || []).filter((id) => id !== task.id))} />{task.taskName} · 长者 #{task.residentId}</label>)}</fieldset><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary" disabled={working}>创建交接</button></div></form>;
  return null;
}

function tasksForHandover(tasks) { return tasks.filter((task) => task.status === "COMPLETED" || task.status === "EXCEPTION"); }
